version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: darbot_postgres_container
    environment:
      POSTGRES_DB: darbot_db
      POSTGRES_USER: darbot_user
      POSTGRES_PASSWORD: darbot123
    ports:
      - "5432:5432"
    volumes:
      - pgdata_darbot:/var/lib/postgresql/data
    networks:
      - darbot_network

  backend:
    build: ./backend
    container_name: darbot_backend_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    networks:
      - darbot_network

volumes:
  pgdata_darbot:

networks:
  darbot_network:
    driver: bridge