# Nombre de la aplicación
spring.application.name=darbot

# Configuración de Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/darbot_db
spring.datasource.username=darbot_user
spring.datasource.password=darbot123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor backend
server.port=8080